### ISSUE TITLE
Convert the whole website to a single page application using AngularJS components

### ISSUE THREAD

**Issue by devcer** [webvr-india/webvr-india.github.io#22]

**Comment by tushararora** [comment]
@viswanathamsantosh

Well I have not been contributing to this website but just want to ask if using AngularJS components is a good idea over using a templating engine like Jade / Nunjucks?

It is a static site so using good old html templates (or using ^templating engine) would suffice with some javascript sprinkled here and there. Using AngularJS is a big overhead in terms of page load time and maintenance.

What do you think?

**Comment by devcer** [comment]
I was suggesting using jade/jstache for writing templates over angularjs(as a templating engine) for the single page website. Does jade has an included templating engine without needing any external framework except vanillaJS? if yes then we can do this.

**Comment by gurumukhi** [comment]
I would like to suggest using jekyll or any similar tool here. @viswanathamsantosh @shahbaz17 @tushararora what do you thing?

Would also like to refer to our old discussion about this at https://github.com/webvr-india/activities/issues/8 where we had similar discussion and we were considering jekyll for this. Positive things about jekyll:
- Very easily maintainable (this is a very big factor as we would want to keep adding stuffs more than one in month). We just need to update content using .md files to update the website.
- Simple and nice themes are already available (https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/)
- Many mozilla sites already use jekyll or similar tools (including aframe.io itself), so working on this will also help our community members to contribute to these sites (thanks @shahbaz17 to notice this point and bring into attention here)

**Comment by shahbaz17** [comment]
I am in total favor of Jekyll. 
It's easy to implement and the best thing is that many of the Mozilla website such as [Global Sprint](https://mozilla.github.io/global-sprint/) and [Activate Mozilla](http://activate.mozilla.community/) is running on Jekyll.

**Long Term Goal**
Contributors of this website then will be able to work on most of the Mozilla's website based on Jekyll.

**Comment by shahbaz17** [comment]
Found https://github.com/jekyll/jekyll/wiki/Sites where we have lots of template to start with.

**Comment by lavish205** [comment]
I'll vote for jekyll, It's easy to build and maintain and more over github officially supports jekyll as their templating engine for github pages.

**Comment by lavish205** [comment]
closing this issue as we have finalized jekyll.
