### ISSUE TITLE
Website content proposal

### ISSUE THREAD

**Issue by gurumukhi** [webvr-india/webvr-india.github.io#26]
Current proposal at https://docs.google.com/document/d/1L4LyqG1KJ5jkNbooN8yK4G2nSy0dHjVVOYqBYh4_yUM/edit?usp=sharing

Menu proposed -
- Home
- Getting started
- Community
- Blog

**Comment by shahbaz17** [comment]
https://github.com/webvr-india/jekyll-website/issues/4
